config/routes.rb
SalomonWww::Application.routes.draw do
  get '/404', :to => 'error#not_found'

  get 'video/index'

  namespace :admin do
    get 'category/assign_product_to_category'
  end



  #scope :path => "(:locale)", :shallow_path => "(:locale)", :locale => /en-US|de-CH|de-DE|en-UK|fr-CH|fr-FR|ru-RU/ do
  localized do
    get '/' => 'home#index', :as => 'home'
    get 'faq' => 'home#faq', :as => 'faq'
    get 'contact/ok' => 'home#contact_ok', :as => 'contact_ok'
    get 'contact' => 'home#contact', :as => 'contact'
    get 'terms' => 'home#terms', :as => 'terms'
    get 'privacy_policy' => 'home#privacy_policy', :as => 'privacy_policy'
    get 'warranty' => 'home#warranty', :as => 'warranty'
    get 'stores' => 'store#index', :as => 'store'
    get 'videos' => 'video#index', :as => 'video'
    get 'team' => 'team#index', :as => 'team'
    get 'team/rider-(:team_member)' => 'team#show', :as => 'team_member'
    get 'team(/:category)' => 'team#index', :as => 'team'
    get 'gear' => 'product#overview', :as => 'product_overview'
    get 'gear/(:category)' => 'product#index', :as => 'products'
    get 'gear/(:category)/(:product)' => 'product#show', :as => 'product_show'

  end

  # legacy redirects
  #Redirects
  get 'salomon-gear.html' => redirect('/')
  get 'teams' => redirect('/team')
  get 'dealers' => redirect('/')
  get '/catalog/product/view/id/:id/s/(:slug)-(:variant)/category/(:cat)' => 'product#legacy'



  root :to => 'home#index'

end

app/views/shared/basic_page.html.haml
- content_for(:navclass) do
  sticky

- content_for(:page_title) do
  #{page.title}

#page-header
  %h1= page.title

%section.main
  .row
    .column.medium-8.medium-offset-2.middle-10.middle-offset-1.small-12{:class => page.pid}
      = raw page.html

%script
  window.sf_url = "#{Rails.application.config.sales_force_url }";

app/views/shared/footer.haml
.row
  %footer

    .large-12.columns
      .footer-slogan
        = image_tag 'layout/slay-footer@2x.png'

    .large-3.columns
      .footer-logo
      .copyright
        %div
        #{ t 'footer.copyright', scope: :salomon }

    .large-2.columns
      %nav.collapseable
        %h5 #{t 'footer.headings.social', scope: :salomon}
        %ul.social
          %li
            %a.ss-facebook{:href=>'https://www.facebook.com/salomonsnowboards', :target=>'_blank'} Facebook
          %li
            %a.ss-twitter{:href=>'https://twitter.com/Salomonsnow', :target=>'_blank'} Twitter
          %li
            %a.ss-tumblr{:href=>'http://salomonsnowboards.tumblr.com/', :target=>'_blank'} Tumblr
          %li
            %a.ss-instagram{:href=>'http://instagram.com/salomonsnowboards', :target=>'_blank'} Instagram
          %li
            %a.ss-vimeo{:href=>'https://vimeo.com/salomonsnowboards', :target=>'_blank'} Vimeo
          %li
            %a.ss-youtube{:href=>'https://www.youtube.com/user/Salomonsnowboarding', :target=>'_blank'} YouTube

    .large-2.columns
      %nav.collapseable
        %h5 Salomon
        %ul
          %li
            %a{:href=>'http://salomonsnowboards.tumblr.com/', :target => '_blank'} Blog
          %li= link_to t('pages.team', scope: :salomon), main_app.team_path
          - unless Rails.env.production?
            %li= link_to t('pages.faq', scope: :salomon), main_app.faq_path

    .large-2.columns
      %nav.collapseable
        %h5 #{ t 'footer.headings.customer_service', scope: :salomon}
        %ul
          - unless Rails.env.production?
            %li= link_to t('pages.warranty', scope: :salomon), main_app.warranty_path
            %li= link_to t('pages.contact', scope: :salomon), main_app.contact_path
          %li= link_to t('pages.terms', scope: :salomon), main_app.terms_path
          %li= link_to t('pages.privacy_policy', scope: :salomon), main_app.privacy_policy_path


    .large-3.columns
      .footer-language-chooser
        %h5 #{t 'footer.change_country', scope: :salomon }
        %a.button
          = A2::Country.find_by(:locale => I18n.locale ).name
      .newsletter
        %h5 #{t 'footer.newsletter_signup_head', scope: :salomon }
        .newsletter-subhead #{t 'footer.newsletter_signup_subhead', scope: :salomon }
        %form.custom.footer-email-subscription
          %input#footer-email-input{:type=>'text', :placeholder => 'your@email.address'}
          %input.button{:type=>'submit', :value=>'Go'}

app/views/shared/head.haml
%head
  %meta{:charset => "utf-8"}

  /
    \ ______                  ______
    |  ____|                 | ____|
    | |__ ___  _ __ _ __ ___ | |__
    |  __/ _ \| '__| '_ ` _ \|___ \
    | | | (_) | |  | | | | | |___) |
    |_|  \___/|_|  |_| |_| |_|____/

    Design and front-end development by Form5.
    www.form5.is
    @Form5
    hello@form5.is

    http://www.salomonsnowboard.com/humans.txt


  %title=content_for?(:page_title) ? yield(:page_title) + ' - Salomon Snowboards' : 'Salomon Snowboards – Snowboards, Snowboard Boots, Snowboard Bindings, & Backcountry Tools'

  - if content_for?(:page_description)
    %meta{:name => "description", :content => "#{yield(:page_description)}"}

  %meta{:name => 'keywords', :content=>'snowboarding, jackets, pants, accessories, apparel, freeride, freestyle, snowboard, boots, salomon, snowboards, snowboard boots, apparel, bindings, jib, park, snowboard bindings, all mountain, splitboards, backcountry snowboarding, backcountry snowboards'}
  %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}

  %link{:rel => "author", :href => "http://www.salomonsnowboard.com/humans.txt", :type=>'text/plain'}

  %meta(property="og:title" content="Salomon Snowboards")
  %meta(property="og:description" content="We challenge the status quo, push boundaries, and critically damage preconceived notions of what riding gear can be. Ride It For Real, Stay Loose and once and for all, Slay Boredom")
  %meta{:property=>"og:image", :content=>'http://d3cqijb9lxupm5.cloudfront.net/assets/salomon-facebook-8eef278188c1039240f2ce44c57a1b23.jpg'}
  %meta(property="og:image:type" content="image/jpg")
  %meta(property="og:image:width" content="1200")
  %meta(property="og:image:height" content="627")

  %link{:href => "#{image_path('ico/favicon.ico')}", :rel => "shortcut icon"}/
  %link{:href => "#{image_path('ico/apple-touch-icon-144-precomposed.png')}", :rel => "apple-touch-icon-precomposed", :sizes => "144x144"}
  %link{:href => "#{image_path('ico/apple-touch-icon-114-precomposed.png')}", :rel => "apple-touch-icon-precomposed", :sizes => "114x114"}
  %link{:href => "#{image_path('ico/apple-touch-icon-72-precomposed.png')}", :rel => "apple-touch-icon-precomposed", :sizes => "72x72"}
  %link{:href => "#{image_path('ico/apple-touch-icon-57-precomposed.png')}", :rel => "apple-touch-icon-precomposed"}


  %meta{:content => "#{image_path('ico/msapplication-TileImage.png')}", :name => "msapplication-TileImage"}/
  %meta{:content => "#00a3d1", :name => "msapplication-TileColor"}/

  %script{:src => '//fast.fonts.net/jsapi/073e9c52-d31f-4999-af90-1140d74e5711.js'}
  = stylesheet_link_tag 'application'
  = javascript_include_tag 'application_head'

  /[if lt IE 9]
    = javascript_include_tag 'html5shiv'
    = javascript_include_tag 'respond.min'

app/views/shared/javascript.haml
= yield(:javascript_pre)
= javascript_include_tag 'application'
%script{:src => "//assets.pinterest.com/js/pinit.js"}
= yield(:javascript)

app/views/shared/language-selector.haml
#footer-language-modal
  .regions
    %h5.lang-heading
      Choose your
      %br
      region
    .region-list
      - regions.each do |region|
        .lang-list
          %h5= region.name
          %ul
            - region.a2_countries.each do |country|
              %li
                = link_to country.name, "#{url_for_locale(country.locale)}?set_country=#{country.locale}"
  #cancel-button.button
    Cancel

app/views/shared/language.haml
#language-bar
  %ul.right
    %li #{t 'header.change_country', scope: :salomon}
    %li.has-dropdown
      %a
        = A2::Country.find_by(:locale => I18n.locale ).name
      .f-dropdown#lang-dropdown
        .inner
          - regions.each do |region|
            .lang-list
              %h5= region.name
              %ul
                - region.a2_countries.each do |country|
                  %li
                    = link_to country.name, "#{url_for_locale(country.locale)}?set_country=#{country.locale}"



    %li
      %a.ignore{:href=>'#'} #{t 'header.ignore', scope: :salomon}
  %p #{ t 'header.language_notification', scope: :salomon, :country => t(cookies[:country_code].try(:to_sym), :scope => :countries) }

app/views/shared/nav-mobile.haml
-#.searchbar
-#  %input.search-input{:type => 'text', :placeholder => t('header.search_placeholder', scope: :salomon)}
-#  %input{:type => 'submit', :value => 'Submit'}

%nav#off-canvas{:class=>yield(:navclass)}
  %section.main
    %h5 Main
    %ul
      %li.open
        %a{:href => "/gear"}  #{t 'pages.gear', scope: :salomon}
        .drop-wrap
          %ul
            - gear_categories.each do |c|
              %li=link_to c.name,main_app.products_url(:category => c.slug)
      %li= link_to t('pages.team', scope: :salomon), main_app.team_path
      %li= link_to t('pages.videos', scope: :salomon), main_app.video_path
      %li
        %a{:href => "http://salomonsnowboards.tumblr.com/"} #{t 'pages.blog', scope: :salomon}
      -#%li
      -#  %a= link_to t('nav.stores') , store_path
  %section.share
    %h5 Share Salomon
    %ul.right.social-wrap
      %li.social.facebook
        %a.ss-icon.ss-social{:href=>'https://www.facebook.com/salomonsnowboards', :target=>'_blank'} facebook

      %li.social.twitter
        %a.ss-icon.ss-social{:href=>'https://twitter.com/Salomonsnow', :target=>'_blank'} twitter

      %li.social.instagram
        %a.ss-icon.ss-social{:href=>'http://instagram.com/salomonsnowboards', :target=>'_blank'} instagram

      %li.social.pinterest
        %a.ss-icon.ss-social{:href=>'http://pinterest.com/salomonsnow/', :target=>'_blank'} pinterest

app/views/shared/nav.haml
-#.searchbar
-#  %input.search-input{:type => 'text', :placeholder => t('header.search_placeholder', scope: :salomon)}
-#  %input{:type => 'submit', :value => 'Submit'}

#nav-container{:class=>yield(:navclass)}
  %nav.top-bar
    %section.top-bar-section
      .canvas-toggle.ss-icon.ss-standard.ss-rows
      =link_to 'Salomon Snowboards', main_app.home_path, class: 'logo'
      / Left Nav Section
      %ul.desk-nav.left
        %li.has-dropdown
          %a{:href => "/gear"}  #{t 'pages.gear', scope: :salomon}
          %ul.dropdown
            - gear_categories.each do |c|
              %li=link_to c.name,main_app.products_url(:category => c.slug)
        %li= link_to t('pages.team', scope: :salomon), main_app.team_path
        %li= link_to t('pages.videos', scope: :salomon), main_app.video_path
        %li
          %a{:href => "http://salomonsnowboards.tumblr.com/"} #{t 'pages.blog', scope: :salomon}
        %li
          %a= link_to t('pages.stores', scope: :salomon) , main_app.store_path

      %ul.desk-nav.right.social-wrap
        %li.social.facebook.dropable
          %a.ss-icon.ss-social{:href=>'https://www.facebook.com/salomonsnowboards', :target=>'_blank'} facebook
          .drop
            .inner
              .fb-like-box{"data-header" => "true", "data-href" => "https://www.facebook.com/SalomonSnowboardFans", "data-show-border" => "true", "data-show-faces" => "false", "data-stream" => "false", "data-width" => "292"}

        %li.social.instagram
          %a.ss-icon.ss-social{:href=>'http://instagram.com/salomonsnowboards', :target=>'_blank'} instagram

        %li.social.twitter.dropable
          %a.ss-icon.ss-social{:href=>'https://twitter.com/Salomonsnow', :target=>'_blank'} twitter
          .drop
            .inner
              %a.twitter-follow-button{"data-show-count" => "false", "data-size" => "large", :href => "https://twitter.com/Salomonsnow"} Follow
              :javascript
                !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');

        %li.social.pinterest.dropable
          %a.ss-icon.ss-social{:href=>'http://pinterest.com/salomonsnow/', :target=>'_blank'} pinterest
          .drop
            .inner
              %a{"data-pin-do" => "buttonFollow", :href => "http://pinterest.com/salomonsnow/"} Salomon Snowboards