config/routes.rb
SalomonWww::Application.routes.draw do
  get '/404', :to => 'error#not_found'

  get 'video/index'

  namespace :admin do
    get 'category/assign_product_to_category'
  end



  #scope :path => "(:locale)", :shallow_path => "(:locale)", :locale => /en-US|de-CH|de-DE|en-UK|fr-CH|fr-FR|ru-RU/ do
  localized do
    get '/' => 'home#index', :as => 'home'
    get 'faq' => 'home#faq', :as => 'faq'
    get 'contact/ok' => 'home#contact_ok', :as => 'contact_ok'
    get 'contact' => 'home#contact', :as => 'contact'
    get 'terms' => 'home#terms', :as => 'terms'
    get 'privacy_policy' => 'home#privacy_policy', :as => 'privacy_policy'
    get 'warranty' => 'home#warranty', :as => 'warranty'
    get 'stores' => 'store#index', :as => 'store'
    get 'videos' => 'video#index', :as => 'video'
    get 'team' => 'team#index', :as => 'team'
    get 'team/rider-(:team_member)' => 'team#show', :as => 'team_member'
    get 'team(/:category)' => 'team#index', :as => 'team'
    get 'gear' => 'product#overview', :as => 'product_overview'
    get 'gear/(:category)' => 'product#index', :as => 'products'
    get 'gear/(:category)/(:product)' => 'product#show', :as => 'product_show'

  end

  # legacy redirects
  #Redirects
  get 'salomon-gear.html' => redirect('/')
  get 'teams' => redirect('/team')
  get 'dealers' => redirect('/')
  get '/catalog/product/view/id/:id/s/(:slug)-(:variant)/category/(:cat)' => 'product#legacy'



  root :to => 'home#index'

end

app/controllers/product_controller.rb
class ProductController < BaseController

  def overview

  end

  def index

    @category = A2::ProductCategory.find_by_slug(params[:category]) || not_found
    page @category.slug

    if stale?(:etag => create_etag([@category.updated_at, page.updated_at]))

      @feature_types = A2::ProductFeatureType.includes(:product_features).where(:id => @category.filters.split(',')) unless @category.filters.blank?
      @products = Rails.cache.fetch(@category) { @category.products.visible.where(:season => '20140') } #

      respond_to do |f|
        f.html
      end
    end

  end

  def show
    @product = A2::Product.cached_product_by_slug(params[:product]) || not_found
    page "#{params[:category]}-product"

    if stale?(:etag => create_etag([@product.updated_at, page.updated_at]))
      respond_to do |f|
        f.html
      end
    end
  end

  def legacy
    product = A2::Product.cached_product_by_slug(params[:slug]) || not_found
    redirect_to product_show_url(:product => params[:slug],:category => product.categories[0].slug), status: :moved_permanently
  end


end

app/helpers/product_helper.rb
module ProductHelper

  def get_size_variants
    unless @product.product_variants.length == 1
      render :partial => 'product_size_thumbs', :locals =>
      { :variants => @product.product_variants }
    end
  end

  def get_color_variants
    unless @product.product_color_variants.length == 1
      render :partial => 'product_color_thumbs',
             :locals => { :variants => @product.product_color_variants }
    end
  end

  def hide_buy_button?
    params[:locale].casecmp('en').zero?
  end

  def salomon_link(slug)
    c = A2::Country.find_by( :locale => I18n.locale.to_s)
    "#{Rails.application.config.salomon_url}#{c.salomon_locale}/product/#{slug}.html"
  end

  def set_asset_type(asset_type)
    if asset_type == 'A2::ImageAsset'
      {:class => 'vimeo'}
    elsif asset_type == 'A2::VideoAsset'
      {:class => 'product-image'}
    end
  end

  def set_lightbox_href(asset)
    if asset.type == 'A2::ImageAsset'
      {:href => cl_image_path(asset.img, :width => 1000, :height => 800, :crop => :fill), :title => asset.title, :data => {:group => 'product-media'}}
    elsif asset.type == 'A2::VideoAsset'
      {:href => "http://player.vimeo.com/video/" + asset.video_url + "?title=0&byline=0&portrait=0", :title => asset.title, :data => {:group => 'product-media'}}
    end

  end


end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/product/_gallery_riders.html.haml
.product-assets
  .large-4.medium-12.middle-4.columns
    - unless product.team_members.empty?
      %h2 Riders
      %ul.riders
        - product.team_members.each do |tm|
          %li{set_text_length_class(tm.name, 14)}
            =link_to(tm.name, tm)
  .large-8.medium-12.middle-8.columns.product-gallery
    - unless product.assets.empty?
      %h2 Gallery
      %ul.large-block-grid-4
        - product.assets.each do |asset|
          %li{set_asset_type(asset.type)}
            %a.html5lightbox{set_lightbox_href(asset)}
              = cl_image_tag asset.img, :width => 80, :height => 80, :crop => 'fill', :onload => 'form5image.hasLoaded(this)', :alt => asset.title

app/views/product/_image_asset.html.haml
Video

app/views/product/_product_color_thumbs.html.haml
:javascript
  var imageSet = new Array();

.product-meta
  %h5 Color
  %ul.product-thumbs
    - variants.each_with_index do |color, colorIndex|
      %li{:class => (colorIndex == 0?'selected':'')}
        :javascript
          imageSet[#{colorIndex}] = new Array();
        = link_to cl_image_tag(color.image, :width => 100, :height => 100, :crop => :fill), '#', :class => 'imageset', :data => {:imagesetindex => "#{colorIndex}"}
        - color.product_images.each_with_index do |variant, imgIndex|
          :javascript
            imageSet[#{colorIndex}][#{imgIndex}] = {
              fullsize: '#{cl_image_path(variant.img, :width=>'580', :height =>'500', :crop => 'fit')}',
              thumb: '#{cl_image_path(variant.img, :width=>'80', :height =>'80', :crop => 'fit')}'
            };

app/views/product/_products_color_thumbs.html.haml
.variants
  %ul.product-thumbs.product-colors
    - variants.each_with_index do |color, colorIndex|
      %li{:class => (colorIndex == 0?'selected':'')}
        = link_to(cl_image_tag( color.image, :width => 50, :height => 50, :alt => color.name, :crop => :fill), '#', :class => 'imageset', :data => {:fullsize => cl_image_path(color.image, :width =>200, :crop => 'fill')})

app/views/product/_products_size_thumbs.html.haml
.variants
  %ul.product-thumbs.product-sizes
    - variants.each_with_index do |size, index|
      - if size.product_image
        %li{:class => (index == 0?'selected':'')}
          %a.button{:href=>'#', :data => {:fullsize => prepend_snowboard_crop(cl_image_path(size.product_image.img,  :width => 180, :height=>386, :crop => :fill, :class => 'product-image'))}}=size.size

app/views/product/_related_gear.html.haml
%section#product-list
  .row
    %h2 Related gear
    - products.each do |product|
      .large-3.columns
        .product
          .main-info
            - if product.is_snowboard?
              - img_loader do
                = link_to prepend_snowboard_crop(cl_image_tag(product.master_image,  :width => 180, :height=>386, :alt => product.name, :crop => :fill, :class => 'product-image', :onload => 'form5image.hasLoaded(this)')), product_show_path(:category => product.categories[0], :product => product.slug)
              %h2{set_text_length_class(product.name, 16)}
                = link_to product.name, product_show_path(:category => product.categories[0], :product => product.slug)
              .price= product_price(product)

            - else
              - img_loader do
                = link_to cl_image_tag(product.master_image,  :width => 200, :alt => product.name, :crop => :fill, :class => 'product-image', :onload => 'form5image.hasLoaded(this)'), product_show_path(:category => product.categories[0], :product => product.slug)
              %h2{set_text_length_class(product.name, 16)}
                = link_to product.name, product_show_path(:category => product.categories[0], :product => product.slug)
              .price= product_price(product)

app/views/product/_tech_feature_list.html.haml
%ul.tech-list
  -list.each do |feature_name, features|
    %li
      %a.expand{:href=>'#'} &#x002B;
      %span
        %b=feature_name
        =(features.map(&:name)).join(", ")
      %ul.more
        - features.each do |feature|
          - if feature.description
            %li
              %h5=feature.name
              %p=feature.description

app/views/product/_tech_panel.html.haml
%section.panel#tech
  .row
    - if product.features_by_type.count > 0
      %h2 Technology
      - slice_count = (product.features_by_type.count/2)
      - feature_count = product.features_by_type.count
      - if feature_count % 2 == 1
        - slice_count += 1
      - list1, list2 = product.features_by_type.in_groups_of(slice_count, false)
      .large-6.columns.tech-list-wrap
        = render :partial => 'tech_feature_list', :locals => { :list =>list1 }
        %a.button.show-more.js-expand-tech-list-wrap Show more
      .large-6.columns.tech-list-wrap
        = render :partial => 'tech_feature_list', :locals => { :list =>list2 }

    - if product.is_snowboard?
      = render :partial => 'tech_sizing_info', :locals => { :variants => product.product_variants }

app/views/product/_tech_sizing_info.html.haml
#sizing-info.row
  %h2 Sizing information
  %section
    %ul.tabs
      - variants.each_with_index do |variant, index|
        %li{:class => (index == 0?'selected':'')}
          %a.button{:href=>'#', :data=>{:variant=>variant.size}}=variant.size

  - variants.each_with_index do |variant, index|
    .tab-content.mobile-inactive{:class => (index == 0?'active':''), :data=>{:variant=>variant.size}}
      %ul.tech-stats
        -variant.tech_specifications.each do |spec|
          %li
            %span=spec.tech_definition_name
            %span=spec.value

app/views/product/index.html.erb
<h1>Product#index</h1>
<p>Find me in app/views/product/index.html.erb</p>
<% @products.each do |product| %>
    <%= product.name %><br/>
<% end %>

app/views/product/index.html.haml
- content_for :bodyclass do
  subpage

- content_for :navclass do
  sticky

- content_for :page_title do
  #{@category.name}

- cache [I18n.locale,page,@category] do
  %section#filterbar
    .row.filter-text
      .large-12.columns
        .row
          .large-8.large-offset-2
            %h1=page.title

    .filters
      .group
        %h4 Rider
        %ul.filter-list
          %li.active(data-filter="all" data-dimension="gender")
            %a.button{:href=>'#'} All
          %li(data-filter="filter-M filter-U" data-dimension="gender")
            %a.button{:href=>'#'} Men
          %li(data-filter="filter-W filter-U" data-dimension="gender")
            %a.button{:href=>'#'} Women
          %li(data-filter="filter-K" data-dimension="gender")
            %a.button{:href=>'#'} Youth

      - @feature_types.each_with_index do |filter, index|
        .group
          %h4=filter.name
          %ul.filter-list
            %li.active(data-filter="all" data-dimension="feature-#{filter.id}")
              %a.button{} All
            - filter.product_features.each do |feature|
              %li(data-filter="filter-#{feature.id}" data-dimension="feature-#{filter.id}")
                %a.button{set_text_length_class(feature.name, 10)}=feature.name

    %a.button.show-filters{:href=>'#'} Show filters

  %section#main
    .row
      #product-list.js-equalize
        -@products.each do |product|
          - filterClasses = product.product_features.map { |p| "filter-#{p.id}" }.join ' '
          - filterClasses << " filter-#{product.gender}"
          .large-3.medium-4.middle-6.columns.mix{:class=>filterClasses, :data => {:name => "#{product.name}", :price => "#{product.price}"}}
            .product.js-equalize-me{:class => (product.is_snowboard? ? 'snowboard':'')}
              .main-info
                - if product.is_snowboard?
                  - img_loader do
                    = link_to prepend_snowboard_crop(cl_image_tag(product.master_image,  :width => 180, :height => 386, :alt => product.name, :crop => :fill, :class => 'product-image', :onload => 'form5image.hasLoaded(this)')), product_show_path(:category => params[:category], :product => product.slug)
                  %h2{set_text_length_class(product.name, 16)}
                    = link_to product.name, product_show_path(:category => params[:category], :product => product.slug)
                  .price= product_price(product)
                  = render :partial => 'products_size_thumbs', :locals => { :variants => product.product_variants }
                - else
                  - img_loader do
                    = link_to cl_image_tag(product.master_image,  :width => 200, :alt => product.name, :crop => :fill, :class => 'product-image', :onload => 'form5image.hasLoaded(this)'), product_show_path(:category => params[:category], :product => product.slug)
                  %h2{set_text_length_class(product.name, 16)}
                    = link_to product.name, product_show_path(:category => params[:category], :product => product.slug)
                  .price= product_price(product)
                  = render :partial => 'products_color_thumbs', :locals => { :variants => product.product_color_variants_with_image }

              .more-info
                .feature
                  %span= t("gender.#{product.gender}",:scope => :salomon, :count => 2) + " " + @category.name_singular
                - product.features_by_type(overview_only=true).each do |feature_name, feature|
                  .feature
                    %h5=feature_name
                    %span=feature.map(&:name).join(", ")

        .large-3.medium-4.middle-6.columns.end.notfound
          .product.last.js-equalize-me
            %h2 Sorry - No products match this filter criteria
            %ul.links
              %li.clear-filters
                %a{:href=>'#'} Clear filters
              %li
                %a Back to front page

        .large-3.medium-4.middle-6.columns.end
          .product.last.lastproduct.js-equalize-me
            %h2
              You've reached
              %br
              the last
              %br
              product
            %ul.links
              %li
                %a.modify-filters{:href=>'#filterbar'} Modify filters
              %li.clear-filters
                %a{:href=>'#'} Clear filters
              %li
                =link_to 'Back to front page', home_path

app/views/product/legacy.html.haml
%h1{:style => 'padding-top:120px'} Product
%h4=  params[:slug]

app/views/product/overview.html.haml
- content_for(:bodyclass) do
  gear

- content_for(:navclass) do
  sticky

#page-header
  .row
    .large-8.large-offset-2.columns
      %h1 Gear

%section#gear
  .row
    - gear_categories.each do |c|
      .large-12.columns.cat{:class => c.name}
        .content
          %h2=c.name
          =link_to 'See all',products_url(:category => c.slug), :class => 'button'

app/views/product/show.html.haml
- content_for(:bodyclass) do
  product

- content_for(:navclass) do
  sticky

- content_for(:page_title) do
  - cache ['page_title',I18n.locale ,@product] do
    #{@product.name} #{@product.categories[0].name_singular}

- content_for(:page_description) do
  - cache ['page_description',I18n.locale ,@product] do
    #{@product.description}

- cache [I18n.locale ,@product] do
  %section#breadcrumbs
    %ul
      %li Your Location
      %li Gear
      %li=link_to @product.categories[0].name,products_path(:category => @product.categories[0])
      %li=link_to @product.name, product_show_path(:product => @product.slug)

%section#main.product-details
  .row
    .medium-6.columns
      .product-main-image
        - img_loader do
          - if @product.is_snowboard?
            = prepend_snowboard_crop(cl_image_tag(@product.master_image, :width=>'580', :height => '500', :alt => @product.name, :crop => 'fit', :onload => 'form5image.hasLoaded(this)'))
          - else
            = cl_image_tag(@product.master_image, :width=>'580', :height => '500', :alt => @product.name, :crop => 'fit', :onload => 'form5image.hasLoaded(this)')
      .product-thumbnails
        %ul
          - @product.product_color_variants[0].product_images.each_with_index do |thumb, i|
            %li{:class => (i == 0?'active':'')}
              .overlay-wrapper
                = link_to cl_image_tag(thumb.img, :width=>'80', :height=>'80', :crop =>'fit', :data=>{:fullsize=>cl_image_path(thumb.img, :width=>'580', :height=>'500', :alt => @product.name, :crop => 'fit')}), '#'
              %a{:href=>'#'} View #{i+1}
    .medium-6.columns
      .product-info-upper
        %h1= @product.name
        %span
          != t("gender.#{@product.gender}", :count => 2, scope: :salomon) + " " + @product.categories[0].name_singular
          != " &mdash; #{@product.tag_line}" if @product.tag_line
        %h2= product_price(@product)
        %form.custom
          - if @product.is_snowboard?
            = get_size_variants
          - else
            = get_color_variants

          = link_to 'Buy now',salomon_link(@product.slug), :target => '_blank', :class => 'button' unless hide_buy_button?
      .product-model
        %span= "MODEL #{@product.article_code}"

        .social
          %span.st_facebook{:displaytext => ""}
          %span.st_twitter{:displaytext => ""}
          %span.st_pinterest{:displaytext => ""}
          %span.st_email{:displaytext => ""}

      :javascript
        var switchTo5x=true;
      %script{:src => "http://w.sharethis.com/button/buttons.js", :type => "text/javascript"}
      :javascript
        stLight.options({publisher: "189e17d4-21f7-4409-bfe6-d6939f7c6693", doNotHash: true, doNotCopy: true, hashAddressBar: false});

      %p.product-description=@product.description

      = render :partial => 'gallery_riders', :locals => { :product => @product }
  = render :partial => 'tech_panel', :locals => { :product => @product }

  - if @product.products.length > 0
    = render :partial => 'related_gear', :locals => { :products => @product.products }