config/routes.rb
SalomonWww::Application.routes.draw do
  get '/404', :to => 'error#not_found'

  get 'video/index'

  namespace :admin do
    get 'category/assign_product_to_category'
  end



  #scope :path => "(:locale)", :shallow_path => "(:locale)", :locale => /en-US|de-CH|de-DE|en-UK|fr-CH|fr-FR|ru-RU/ do
  localized do
    get '/' => 'home#index', :as => 'home'
    get 'faq' => 'home#faq', :as => 'faq'
    get 'contact/ok' => 'home#contact_ok', :as => 'contact_ok'
    get 'contact' => 'home#contact', :as => 'contact'
    get 'terms' => 'home#terms', :as => 'terms'
    get 'privacy_policy' => 'home#privacy_policy', :as => 'privacy_policy'
    get 'warranty' => 'home#warranty', :as => 'warranty'
    get 'stores' => 'store#index', :as => 'store'
    get 'videos' => 'video#index', :as => 'video'
    get 'team' => 'team#index', :as => 'team'
    get 'team/rider-(:team_member)' => 'team#show', :as => 'team_member'
    get 'team(/:category)' => 'team#index', :as => 'team'
    get 'gear' => 'product#overview', :as => 'product_overview'
    get 'gear/(:category)' => 'product#index', :as => 'products'
    get 'gear/(:category)/(:product)' => 'product#show', :as => 'product_show'

  end

  # legacy redirects
  #Redirects
  get 'salomon-gear.html' => redirect('/')
  get 'teams' => redirect('/team')
  get 'dealers' => redirect('/')
  get '/catalog/product/view/id/:id/s/(:slug)-(:variant)/category/(:cat)' => 'product#legacy'



  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < BaseController

  def index
    page 'home'
    puts "#{Cashier.tags} tags2"

    @team_category = A2::TeamCategory.select([:id,:updated_at]).find_by_slug(:pros)

    @vimeo = A2::VimeoFeed.cached_latest
    @instagram = A2::InstagramFeed.latest_by_user('salomonsnowboards')
    @facebook = A2::FacebookFeed.cached_latest_with_limit(2,true)

    respond_to do |f|
      f.html
    end

  end

  def contact
    page 'contact'
    render 'shared/basic_page'
  end

  def contact_ok
    page 'contact_ok'
    render 'shared/basic_page'
  end

  def terms
    page 'terms'
    render 'shared/basic_page'
  end

  def privacy_policy
    page 'privacy_policy'
    render 'shared/basic_page'
  end

  def warranty
    page 'warranty'
    render 'shared/basic_page'
  end

  def faq
    page 'faq'
    render 'shared/basic_page'
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/partials/hero-video.html.haml
- banner 'home-hero' do |b|
  - if mobile_device?
    %section#hero-mobile.flex-video.vimeo.widescreen
      %iframe{ :src => "//player.vimeo.com/video/#{b.video.split('/').slice(-1)}?color=00a4d1&amp;autoplay=1&title=0&byline=0", :webkitallowfullscreen => '', :mozallowfullscreen => '' ,:allowfullscreen => ''}
  - else
    %section#hero.has-video{'data-video' => b.video , :style => "background-image: url(#{cl_image_path(b.image)})"}
      #play-overlay
        -#= image_tag('layout/hero_video_overlay.png', :alt => 'Play video')
        %empty{:style =>'height: 350px;width:200px;display:block'}
        %a.button{:href=>'#'} Click to play
      %video.ambient{:autoplay=>'', :loop=>'loop', :muted => 'muted'}
        -# = image_tag('hero/freestyle_arsenal.jpg', :alt => 'Play video')
        -# %source{:src=>'http://vimeo.com/73305457/download?t=1377699115&v=186168904&s=31a2c503c0e8ff66330fd3173c4564a8', :type=>'video/mp4'}/
        -# %source{:src=>'http://a2.form5.is/assets/hero-ambient-video-cropped.ogv', :type=>'video/ogg'}/

app/views/home/partials/hero.html.haml
%section#hero
  .row
    .hero-text
      %h2
        %div Hologram bindings
        %div featuring
        %div shadow fit
      .price
        From $39.95
      %a{:href => 'product.html', :class => 'button large-button'}
        View product

app/views/home/partials/newsletter.html.haml
%section#newsletter
  .row
    .large-5.columns
      .call-out

        %h3 Subscribe, stay connected & save

        %form.email-subscription
          %div
            %input#email-input.large-input{:type => 'text',:placeholder => 'E-mail Address'}
          %div
            %input.button.small-button{:type => 'submit', :value => 'Submit'}

    .large-4.columns.large-offset-3
      %h3 Stay connected
      %ul
        %li
          %a{:class=>'facebook', :href => 'https://www.facebook.com/SalomonSnowboardFans', :target=>'_blank'}
            %span Facebook
        %li
          %a{:class=>'twitter', :href => 'https://twitter.com/Salomonsnow', :target=>'_blank'}
            %span Twitter
        %li
          %a{:class=>'tumblr', :href => '#', :target=>'_blank'}
            %span Tumblr
        %li
          %a{:class=>'instagram', :href => 'http://instagram.com/salomonsnowboards', :target=>'_blank'}
            %span Instagram

app/views/home/partials/product-feature.html.haml
%section#product-feature
  //= image_tag 'frontpage/slay-boredom.png', :class => 'boredom'
  .row
    - banner 'home-product-feature-image' do |b|
      .large-6.columns.large.feature-image
        = cl_image_tag(b.image)
    - banner 'home-product-feature-text' do |b|
      .large-6.columns.large.feature-text
        %h2= raw b.title
        =cl_image_tag b.image, :class=>'new-logo'
        %h3= raw b.subtitle

        %p= b.content
        =link_to b.link_text , b.link_url , :class => 'button'

app/views/home/partials/team.html.haml
- cache [team_category] do
  %section#the-team
    .row
      %h2 Team
      .large-12.columns
        .team-members
          .row
            - team_category.team_members.each do |tm|
              .large-3.medium-4.middle-6.small-12.columns
                .team-member.img-zoom-hover
                  .team-member-info
                    %h2
                      =link_to(tm.name, team_member_path(:team_member => tm.slug))
                    .team-member-country= tm.country
                  = cl_image_tag(tm.thumb_image, :width => 285, :height => 285, :alt => tm.name, :crop => 'fill', :alt => tm.name)
        = link_to('See the full team', team_path, :class =>'button')

app/views/home/partials/updates.html.haml
%section#updates
  .row
    %h2 Updates

    // Vimeo column
    .large-6.medium-12.columns
      .update-item.vimeo(data-vimeo-id="#{vimeo.item_id}")
        .update-meta
          %i.ss-icon.ss-standard video
          %p= vimeo.title
          .time-ago=vimeo.relative_date + " ago"
        - img_loader do
          =cl_image_tag(vimeo.img, :width=>540, :height=>304, :crop=>'fill', :gravity=>'face', :onload=>'form5image.hasLoaded(this)', :alt=>vimeo.title)
        .video-player.flex-video.vimeo.widescreen
      %a.button.vimeo{:href=>'http://vimeo.com/salomonsnowboards', :target=>'_blank'} More videos on Vimeo

    // Facebook column
    .large-3.medium-6.small-12.columns
      - facebook.each do |fb|
        .update-item.facebook
          .update-meta
            %i.ss-icon.ss-social facebook
            .time-ago= fb.relative_date + " ago"
          %a{:href=>fb.url, :target=>'_blank'}
            =cl_image_tag(fb.img, :onload=>'form5image.hasLoaded(this)', :alt=>vimeo.title, :height=>100, :width=>100, :crop=>'fill', :gravity=>'face')
          %p
            %a{:href=>fb.url, :target=>'_blank'}=truncate(fb.title, length: 65)
      %a.button.facebook{:href=>'http://facebook.com/salomonsnowboards', :target=>'_blank'} More updates on Facebook


    // Instagram column
    - cache 'home-instagram', :tag => %w('instagram-import')  do
      .large-3.medium-6.small-12.columns
        .update-item.instagram
          .update-meta
            %i.ss-icon.ss-social instagram
            .time-ago= instagram.relative_date + " ago"
          = link_to cl_image_tag(instagram.img, :width=>240, :height=>240, :crop=>'fill', :alt => instagram.title), instagram.url, target: '_blank'
          %p= truncate(instagram.title, length: 100, separator: ' ')
        %a.button.instagram{:href=>'http://instagram.com/salomonsnowboards', :target=>'_blank'} More on Instagram